services:
  backend:
    build: ./backend
    image: learning-backend
    container_name: learning-backend
    ports:
      - "5000:5000"
    environment:
      PORT: "5000"
      MONGO_URI: "mongodb://your-db"
      JWT_SECRET: "some_secret"
    volumes:
      - ./backend/config/firebase-service-account.json:/app/config/firebase-service-account.json
    restart: always


  frontend:
    build: ./frontend
    image: learning-frontend
    container_name: learning-frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    restart: always
