apiVersion: v1
kind: Service
metadata:
  name: learning-platform-frontend
  namespace: learning-platform
spec:
  type: LoadBalancer
  selector:
    app: learning-platform-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
